### PR TITLE
Revert "some fixes i made that fix mostly all of the crash and issues "

### PR DESCRIPTION
**Pull request by DDXofficial**
Reverts DDXofficial/sl86#2

While I appreciate the addition of machine creation code, your changes were based on version 0.1a, which did not have the fixes that I added to the latest version of launcher.py (i.e. 0.2-pre).

Any changes containing your code will be duly attributed going forward.

### CODE REVIEW

**Comment by CypherNebula84** [comment]
i will make new after this
new update

**Comment by CypherNebula84** [comment]
just make Shure if you want to ad the thing so it doesn't crash if something invalid

**Comment by CypherNebula84** [comment]
and i make gui

**Comment by DDXofficial** [comment]
Please, no need to make a GUI. There already are countless GUI-based managers for 86Box.

**Pull request merged**
